#!/bin/bash
sudo pkill -f supervisord  #kill all process supervisord
sudo pip3 install virtualenv
cd /home/ec2-user/app
virtualenv environment
source environment/bin/activate
sudo pip3 install -r requirements.txt